config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'top_pages#top'
  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password]}
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password]}
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :danger

  private

  def not_authenticated
    redirect_to login_path, danger: 'ログインしてください'
  end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def top; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      flash[:success] = 'ログインしました'
      redirect_back_or_to #
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new, status::unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:success] = 'ログアウトしました'
    redirect_to root_path, status::see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = '会員登録に成功しました'
      auto_login(@user)
      redirect_to #
    else
      flash[:danger] = '会員登録に失敗しました'
      render 'new', status::unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_pages_helper.rb
module TopPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealEnglish</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top_pages/top.html.erb
<div class = 'top-wrapper'>
  <div class = 'logo'>
    <%= link_to root_path do %>
      <%= image_tag("", alt: "Logo") %>
      REAL English
    <% end %>
  </div>
</div>

<div class = 'sign-in'>
  <%= link_to '会員登録はこちら', new_user_path, class: 'sign-in-link' %>
</div>
<div class = 'login'>
  <%= link_to 'ログインはこちら', '#', class: 'login-link' %>
</div>

<div class = 'dictionary-public'>
  <%= link_to 'Dictionary', '#', class: 'public-dictionary-link' %>
</div>

<div class = 'how-to-use'>
  <h1>利用方法</h1>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1><%= 'ログイン' %></h1>

        <%= form_with url: login_path do |form| %>
            <div class = "mb-3">
                <%= form.label :email, class: "form-label" %>
                <%= form.text_field :email, class: "form-controll" %>
            </div>
            <div class = "mb-3">
                <%= form.label :password, class: "form-label" %>
                <%= form.password_field :password, class: "form-controll" %>
            </div>
            <%= form.submit 'ログイン', class: "btn btn-primary", data: { disable_with: t(".login")} %>
        <% end %>

      <div class='text-center'>
        <%= link_to '会員登録', new_user_path %>
        <%= link_to 'パスワードを忘れた方はこちら', new_password_reset_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-lg-8 mx-auto">
            <h1>
                <%= 'ユーザー登録' %>
            </h1>
            <%= form_with model: @user do |form| %>

                <div class="mb-3">
                    <%= form.label :name, class: 'form-label' %>
                    <%= form.text_field :name, class: 'form-controll' %>
                </div>
                <div class="mb-3">
                    <%= form.label :email, class: 'form-label' %>
                    <%= form.text_field :email, class: 'form-controll' %>
                </div>
                <div class="mb-3">
                    <%= form.label :password, class: 'form-label' %>
                    <%= form.password_field :password, class: 'form-controll' %>
                </div>
                <div class="mb-3">
                    <%= form.label :password_confirmation, class: 'form-label' %>
                    <%= form.password_field :password_confirmation, class: 'form-controll' %>
                </div>
                <%= form.submit '登録', class: 'btn btn-primary', data: { disable_with: t('helpers.submit.create')} %>
            <% end %>

            <div class='text-center'>
                <%= link_to 'ログインページへ', login_path %>
            </div>
        </div>
    </div>
</div>